### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by theRichu** [turingou/player#30]
var Player = require('player');
var start_player = new Player(__dirname + '/lib/gunshot.mp3');

setInterval(function(){
  start_player.play();

},500)

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Player.addListener (events.js:160:15)
    at Player.play (/Users/TaeYeongKIM/Development/coach-block/node_modules/player/libs/player.js:56:29)
    at Object.<anonymous> (/Users/TaeYeongKIM/Development/coach-block/player_test.js:6:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by turingou** [comment]
The pull request has been merged to branch master, thank you.

**Comment by turingou** [comment]
A new bugfix version `v0.3.2` has been shipped.
