### ISSUE TITLE
node v0.12 无法安装 player

### ISSUE THREAD

**Issue by h1bomb** [turingou/player#32]
单独安装 speaker是可以的。
报错如下：
```
../src/bindings.cc:29:15: error: calling a protected constructor of class
      'v8::HandleScope'
  HandleScope scope;
              ^
/usr/local/lib/node_modules/player/node_modules/lame/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: 
      declared protected here
  V8_INLINE HandleScope() {}
            ^
1 error generated.
make: *** [Release/obj.target/bindings/src/bindings.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/player/node_modules/lame
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm info lame@1.1.1 Failed to exec install script
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "player" "-g" "-d"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.
npm info preuninstall speaker@0.2.1
npm info uninstall speaker@0.2.1
npm info postuninstall speaker@0.2.1
npm info preuninstall lame@1.1.1
npm info uninstall lame@1.1.1
npm info postuninstall lame@1.1.1
npm info preuninstall player@0.3.2
npm info uninstall player@0.3.2
npm info postuninstall player@0.3.2

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Hbomb/npm-debug.log
```

**Comment by turingou** [comment]
node-lame 目前还没有支持 v0.11.x 和 v0.12.x

**Comment by blueandhack** [comment]
node-lame 已经支持 v0.11.x 和 v0.12.x

**Comment by blueandhack** [comment]
请看这里
https://github.com/TooTallNate/node-lame/commit/61f63453f6831a467c21c98ee8916c96c9cacfca

**Comment by turingou** [comment]
感谢 @blueandhack 我升级一下依赖模块版本

**Comment by blueandhack** [comment]
@turingou BTW douban.fm 也因为这个模块的问题 无法安装

**Comment by turingou** [comment]
master 分支的代码已升级，大家可以帮忙在自己的环境上测试下~

**Comment by turingou** [comment]
Hi all
player `v0.4.0` 已经发布，现已支持 Node.js `v0.12.x` 应也支持 iojs 2.0.x
